name: GTK UI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  headless-ui-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and run headless UI tests
        run: |
          docker-compose -f rebuild_plan/docker/docker-compose.yml build test
          docker-compose -f rebuild_plan/docker/docker-compose.yml run --rm test pytest tests/ui/ --headless -v
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/
  
  xwayland-ui-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Xwayland test image
        run: |
          docker-compose -f rebuild_plan/docker/docker-compose.yml build xwayland-test
      
      - name: Run UI tests with Xwayland
        run: |
          chmod +x rebuild_plan/docker/run_xwayland_tests.sh
          ./rebuild_plan/docker/run_xwayland_tests.sh --headless
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: xwayland-test-results
          path: test-results/